delete_rke2_release_assets add repository opt
Signed-off-by: Brooks Newberry <brooks@newberry.com>

diff --git a/bin/delete_rke2_release_assets b/bin/delete_rke2_release_assets
--- a/bin/delete_rke2_release_assets
+++ b/bin/delete_rke2_release_assets
@@ -6,19 +6,23 @@ set -e
 
 usage() {
     echo "This script will delete all assets for a rancher/rke2 release"
-    echo "usage: $0 [t:dh]
+    echo "usage: $0 [t:r:dh]
     -t    release tag
+    -r    repository
     -d    dry run
     -h    show help
 
 examples:
-    $0 -t v1.22.8+rke2r1"
+    $0 -t v1.22.8+rke2r1 -r rancher/rke2"
 }
 
-while getopts "t:dh" opt; do
+while getopts "t:r:dh" opt; do
     case "${opt}" in
         t)
             RELEASE_TAG="${OPTARG}"
+            ;;
+        r)
+            REPOSITORY="${OPTARG}"
             ;;
         d)
             DRY_RUN='true'
@@ -39,11 +43,16 @@ if [ -z "${RELEASE_TAG}" ]; then
     exit 1
 fi
 
+if [ -z "${REPOSITORY}" ]; then
+    echo "error: repository required"
+    exit 1
+fi
+
 has_gh
 
 setup_tmp
 
-DELETIONS=$(gh release view "${RELEASE_TAG}" -R rancher/rke2 --json assets -q '.assets.[] | .name')
+DELETIONS=$(gh release view "${RELEASE_TAG}" -R "${REPOSITORY}" --json assets -q '.assets.[] | .name')
 
 if [ -z "${DELETIONS}" ]; then
     echo "No assets to delete"
@@ -52,9 +61,9 @@ fi
 
 for i in ${DELETIONS}; do
     if [ ${DRY_RUN} ]; then
-        echo "gh release delete-asset ${RELEASE_TAG} ${i} --repo rancher/image-build-kubernetes -y"
+        echo "gh release delete-asset "${RELEASE_TAG}" "${i}" --repo "${REPOSITORY}" -y"
     else
-        gh release delete-asset ${RELEASE_TAG} ${i} --repo rancher/image-build-kubernetes -y
+        gh release delete-asset "${RELEASE_TAG}" "${i}" --repo "${REPOSITORY}" -y
     fi
 done
 
